In [1]:
import pandas as pd
from pathlib import Path

df_transects = pd.read_pickle("../data/pkl/df_transects.pkl")
df_transects.head()

,UID,Name,start_time,turn_time,end_time,lat_from,long_from,lat_turn,long_turn,lat_to,...,Post: Notes on Transect End,Pre: Ecomorphology habitat,Pre: New Transect?,Pre: Notes,Pre: Notes on Transect Start,Pre: OPC Vegetation,Pre: On old reserve?,Pre: Reserve vegetation,Pre: Transect physical habitat,Pre: Transect vegetation
0,271687,48,2011-07-08 16:09:19,2011-07-08 17:38:38,2011-07-08 17:53:34,0.019397,36.944255,0.019248,36.936132,0.019248,...,"ended at 900m, transect end near bushland",open/tree-less,Yes,start just south of road off grants plains,NaN,NaN,Yes,NaN,grass closed,grass
1,274498,49,2011-07-10 14:59:39,2011-07-10 15:21:22,2011-07-12 12:40:34,0.021680,36.941568,0.021160,36.935927,0.021160,...,NaN,open/tree-less,Yes,NaN,a bit north of road,NaN,Yes,NaN,grass closed,grass
2,277434,50,2011-07-12 15:59:36,2011-07-13 15:05:27,2011-07-13 15:56:27,0.022625,36.930758,0.022605,36.939808,0.022625,...,NaN,open/tree-less,Yes,NaN,heading east,NaN,Yes,NaN,grass closed,grass
3,278888,51,2011-07-13 16:09:31,2011-07-15 12:33:06,2011-07-15 12:47:30,0.023828,36.930668,0.023388,36.938127,0.023388,...,NaN,open/tree-less,Yes,NaN,,NaN,Yes,NaN,grass closed,grass
4,285685,52,2011-07-18 09:28:36,2011-07-18 10:31:19,2011-07-18 11:15:07,0.087638,36.828862,0.087870,36.837802,0.087870,...,3 patches of hyena poop,O;WBG,Yes,NaN,transitional between opn and wooded bushed gra...,NaN,No,NaN,grass closed,grass

In [2]:
df_occurrences = pd.read_pickle("../data/pkl/df_occurrences.pkl")
df_occurrences.head()

,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,Lat,Long,Note,State,Post: Age,...,Post: Taxon guess?,Pre: Age,Pre: Distance spotted,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon
0,1,4354089,1,2003-02-17 09:12:35,2003-02-17 17:14:57,0.042495,36.970267,None,Completed,NaN,...,NaN,adult,0,No,No,"flat, open, short grass",,Unknown,3b-4,Bovidae (large)
1,2,4354089,2,2003-02-17 09:17:26,2003-02-17 17:20:34,0.042522,36.966980,None,Completed,NaN,...,NaN,adult,0,No,No,"very short grass, dirt patch, flat and open \n",,Unknown,4,eland
2,3,4354089,3,2003-02-17 09:55:37,2003-02-17 10:05:08,0.042432,36.966908,None,Completed,NaN,...,NaN,old adult,5,No,No,"flat, short grass",,Unknown,4,zebra
3,4,4354089,4,2003-02-17 10:14:26,2003-02-17 10:15:34,0.042495,36.966773,None,Completed,NaN,...,NaN,adult,0,No,No,"dirt patch, flat",,Unknown,0 - unknown,Mammalia indet
4,5,4354089,5,2003-02-17 10:30:03,2003-02-17 16:08:58,0.042549,36.966055,None,Completed,NaN,...,NaN,adult,16,No,No,"flat, very short grass",,Unknown,3,Bovidae (medium)

In [3]:
df_instances = pd.read_pickle("../data/pkl/df_instances.pkl")
df_instances.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,...,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon,Name,DateAdded,AddedBy
0,C3CD24C5-09B7-42DB-A5BE-82C862FCEE6A,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
1,28FC916B-F859-444C-A3B6-24F1040AB291,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,2,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
2,FF2ABC54-0172-4A03-81FE-72BAB7CE4C41,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,3,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
3,43E88323-2CA0-4A29-8552-480BB96E4ACB,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,4,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
4,24D9C6B4-FADC-4706-B09B-80EAD9F15D57,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,5,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick

In [4]:
df_briana_with_responses = pd.read_pickle("../data/pkl/df_briana_with_responses.pkl")
df_briana_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,Are there ecomorphable elements?,Articulated?,Bone notes,Buried - Notes,Buried?,...,UPM lo,UPM4 lc,UPM4 lo,UPM4 wc,UPM4 wo,Upper or lower?,Vertebra Portion,Weathering class,What element is this?,upper or lower?
0,B5E69EAE-E4FF-1B3E-F38B-0EC66DAC8774,1,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,3,calcaneus,NaN
1,789F0CCC-7D1C-816F-F29C-B4E0BB3B82AB,2,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,damage but not sure if caused by carnivore,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,4,hemi-mandible,NaN
2,316C833E-D57B-C57D-6EB9-0F6447D46963,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN
3,17F84367-F24B-B574-F9CC-0CFF4F414BC0,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,2,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN
4,0FF21BFC-21B9-7915-45B2-5D82706B82B5,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,3,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN

In [5]:
df_fire_with_responses = pd.read_pickle("../data/pkl/df_fire_with_responses.pkl")
df_fire_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,Are there ecomorphable elements?,Articulated?,Bone notes,Buried - Notes,Buried?,...,UPM lo,UPM4 lc,UPM4 lo,UPM4 wc,UPM4 wo,Upper or lower?,Vertebra Portion,Weathering class,What element is this?,upper or lower?
0,A4802CC8-E5E0-439E-B6EC-38F3F46836D0,269,DE54448B-7AAD-4E55-B364-795A6F2888A7,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B1AE1CD6-16E1-4C69-80B4-1DC02EBA1F0D,272,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29428771-CDA7-48BA-87ED-6B52BDE512FB,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36390049-5D37-44EB-AEFE-63651658463E,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,2,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EC8379E0-1868-4CD7-9130-89E546E91755,273,114A785B-804D-4AEB-892B-D6116DF31303,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# NISP (# of bones)
# Merge df_instances with df_occurrences (to get TransectUID)
df_instances_with_occ = df_instances.merge(
    df_occurrences[['ID', 'TransectUID']],
    how='inner',
    left_on='OccurrenceID',
    right_on='ID',
    suffixes=('', '_occ')
)

# Merge with df_transects to get the habitat
df_instances_full = df_instances_with_occ.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='inner',
    left_on='TransectUID',
    right_on='UID',
    suffixes=('', '_transect')
)

In [9]:
df_transect_metadata = df_transects.copy()
df_transect_metadata['area_km2'] = df_transect_metadata['distance_km'] * 0.05
mni_per_transect = df_occurrences['TransectUID'].value_counts()
df_transect_metadata['mni_count'] = df_transect_metadata['UID'].map(mni_per_transect).fillna(0).astype(int)
nisp_per_transect = df_instances_full['TransectUID'].value_counts()
df_transect_metadata['nisp_count'] = df_transect_metadata['UID'].map(nisp_per_transect).fillna(0).astype(int)

In [10]:
# DataFrames to Prepare & Save as .pkl
# Name	Description
# df_occurrences_with_taxon	Occurrences + habitat + clean taxon labels
# df_taxon_by_habitat	Taxon abundance matrix by habitat
# df_taxon_by_transect	Taxon abundance matrix by transect
# df_taxon_by_instance (optional)	Taxon occurrence by instance (if needed later)

# 1. Create a clean Taxon label column
df_occurrences['Taxon Label'] = (
    df_occurrences['Post: Taxon guess?']
    .fillna(df_occurrences['Post: taxon guess?'])
    .fillna(df_occurrences['Pre: Taxon'])
)

# 2. Merge with transect metadata to get habitat

df_occurrences_with_taxon = df_occurrences.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='left',
    left_on='TransectUID',
    right_on='UID'
)

# 3. Create composition matrices
# A. Taxon by Habitat
df_taxon_by_habitat = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='Pre: Transect physical habitat',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# B. Taxon by Transect
df_taxon_by_transect = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='TransectUID',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# 4. Save all to pickle files
import os
os.makedirs("data", exist_ok=True)

df_occurrences_with_taxon.to_pickle("../data/pkl/df_occurrences_with_taxon.pkl")
df_taxon_by_habitat.to_pickle("../data/pkl/df_taxon_by_habitat.pkl")
df_taxon_by_transect.to_pickle("../data/pkl/df_taxon_by_transect.pkl")

In [13]:
# !mkdir -p data
# Save the DataFrame to a pickle file
df_transect_metadata.to_pickle("../data/pkl/df_transect_metadata.pkl")

In [12]:
output_path = "../data/export/excel/source_data.xlsx"

with pd.ExcelWriter(output_path, engine='xlsxwriter') as writer:
    df_transects.to_excel(writer, sheet_name='Transects', index=False)
    df_occurrences.to_excel(writer, sheet_name='Occurrences', index=False)
    df_instances.to_excel(writer, sheet_name='Instances', index=False)
    df_briana_with_responses.to_excel(writer, sheet_name='Briana', index=False)
    df_fire_with_responses.to_excel(writer, sheet_name='Fire', index=False)
    df_transect_metadata.to_excel(writer, sheet_name='TransectData', index=False)

print(f"âœ… Excel saved to: {output_path}")

âœ… Excel saved to: ../data/export/excel/source_data.xlsx