In [13]:
import pandas as pd
import numpy as np
import openpyxl
from pathlib import Path

df_transects = pd.read_pickle("../data/pkl/df_transects.pkl")
df_transects.head()

,UID,Name,start_time,turn_time,end_time,lat_from,long_from,lat_turn,long_turn,lat_to,...,Post: Notes on Transect End,Pre: Ecomorphology habitat,Pre: New Transect?,Pre: Notes,Pre: Notes on Transect Start,Pre: OPC Vegetation,Pre: On old reserve?,Pre: Reserve vegetation,Pre: Transect physical habitat,Pre: Transect vegetation
0,271687,48,2011-07-08 16:09:19,2011-07-08 17:38:38,2011-07-08 17:53:34,0.019397,36.944255,0.019248,36.936132,0.019248,...,"ended at 900m, transect end near bushland",open/tree-less,Yes,start just south of road off grants plains,NaN,NaN,Yes,NaN,grass closed,grass
1,274498,49,2011-07-10 14:59:39,2011-07-10 15:21:22,2011-07-12 12:40:34,0.021680,36.941568,0.021160,36.935927,0.021160,...,NaN,open/tree-less,Yes,NaN,a bit north of road,NaN,Yes,NaN,grass closed,grass
2,277434,50,2011-07-12 15:59:36,2011-07-13 15:05:27,2011-07-13 15:56:27,0.022625,36.930758,0.022605,36.939808,0.022625,...,NaN,open/tree-less,Yes,NaN,heading east,NaN,Yes,NaN,grass closed,grass
3,278888,51,2011-07-13 16:09:31,2011-07-15 12:33:06,2011-07-15 12:47:30,0.023828,36.930668,0.023388,36.938127,0.023388,...,NaN,open/tree-less,Yes,NaN,,NaN,Yes,NaN,grass closed,grass
4,285685,52,2011-07-18 09:28:36,2011-07-18 10:31:19,2011-07-18 11:15:07,0.087638,36.828862,0.087870,36.837802,0.087870,...,3 patches of hyena poop,O;WBG,Yes,NaN,transitional between opn and wooded bushed gra...,NaN,No,NaN,grass closed,grass

In [ ]:

# Weathering class lookup
weathering_file = Path("../data/import/excel/Weathering class.xlsx")
df_weathering = pd.read_excel(weathering_file)
# Mapping of weathering class to age ranges
weathering_lookup = df_weathering.set_index("Weathering class")[["Age min", "Age max"]]

In [14]:
df_occurrences = pd.read_pickle("../data/pkl/df_occurrences.pkl")

hi = 'Post: Taxon Guess?'
lo = 'Post: Taxon guess?'

# (optional but recommended) treat blanks/NaN-like strings as real NaN
for c in (hi, lo):
    if c in df_occurrences.columns:
        df_occurrences[c] = (df_occurrences[c]
            .astype(str)
            .str.strip()
            .replace({'': np.nan, 'nan': np.nan, 'NaN': np.nan, 'None': np.nan, 'NULL': np.nan, 'null': np.nan}, regex=False)
        )

# Use lower-g values only where capital-G is null
if lo in df_occurrences.columns:
    df_occurrences[hi] = df_occurrences[hi].combine_first(df_occurrences[lo])  # or: .fillna(df_occurrences[lo])
    df_occurrences = df_occurrences.drop(columns=[lo])

df_occurrences.to_pickle("../data/pkl/df_occurrences.pkl")


df_occurrences.head(10)

,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,Lat,Long,Note,State,Post: Age,...,Post: Taxon Guess?,Pre: Age,Pre: Distance spotted,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon
0,1,4354089,1,2003-02-17 09:12:35,2003-02-17 17:14:57,0.042495,36.970267,None,Completed,NaN,...,Bovidae (large),adult,0,No,No,"flat, open, short grass",,Unknown,3b-4,Bovidae (large)
1,2,4354089,2,2003-02-17 09:17:26,2003-02-17 17:20:34,0.042522,36.966980,None,Completed,NaN,...,eland,adult,0,No,No,"very short grass, dirt patch, flat and open \n",,Unknown,4,eland
2,3,4354089,3,2003-02-17 09:55:37,2003-02-17 10:05:08,0.042432,36.966908,None,Completed,NaN,...,zebra,old adult,5,No,No,"flat, short grass",,Unknown,4,zebra
3,4,4354089,4,2003-02-17 10:14:26,2003-02-17 10:15:34,0.042495,36.966773,None,Completed,NaN,...,Mammalia indet,adult,0,No,No,"dirt patch, flat",,Unknown,0 - unknown,Mammalia indet
4,5,4354089,5,2003-02-17 10:30:03,2003-02-17 16:08:58,0.042549,36.966055,None,Completed,NaN,...,Bovidae (medium),adult,16,No,No,"flat, very short grass",,Unknown,3,Bovidae (medium)
5,6,4354089,6,2003-02-17 10:33:39,2003-02-17 11:17:28,0.042594,36.963046,None,Completed,NaN,...,zebra,adult,9,No,No,"short grass, flat",,Unknown,4,zebra
6,7,4354089,7,2003-02-17 11:33:08,2003-02-17 16:34:29,0.042558,36.962040,None,Completed,NaN,...,zebra,adult,3,No,No,"medium grass, flat",,Unknown,3b-4,Mammalia indet
7,8,4354089,8,2003-02-17 11:41:05,2003-02-17 11:43:31,0.042594,36.962004,None,Completed,NaN,...,zebra,adult,5,No,No,"short to medium grass, flat",,Unknown,4,zebra
8,9,4354089,9,2003-02-17 11:45:56,2003-02-17 11:47:09,0.042608,36.961968,None,Completed,NaN,...,zebra,adult,4,No,No,short grass,,Unknown,4,zebra
9,10,4354089,10,2003-02-17 11:54:30,2003-03-17 20:26:22,0.042639,36.961986,None,Completed,NaN,...,zebra,adult,4,No,No,short grass,,Unknown,4,zebra

In [15]:
df_instances = pd.read_pickle("../data/pkl/df_instances.pkl")
df_instances.head()

df_briana_with_responses = pd.read_pickle("../data/pkl/df_briana_with_responses.pkl")
df_briana_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,...,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon,Name,DateAdded,AddedBy
0,C3CD24C5-09B7-42DB-A5BE-82C862FCEE6A,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
1,28FC916B-F859-444C-A3B6-24F1040AB291,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,2,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
2,FF2ABC54-0172-4A03-81FE-72BAB7CE4C41,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,3,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
3,43E88323-2CA0-4A29-8552-480BB96E4ACB,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,4,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
4,24D9C6B4-FADC-4706-B09B-80EAD9F15D57,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,5,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick

In [ ]:
# Estimate year of death for instances and occurrences
inst_tmp = df_instances.merge(
    df_briana_with_responses[["UID", "Weathering class"]],
    on="UID",
    how="left",
).join(weathering_lookup, on="Weathering class")
inst_tmp["RecordingStartTime"] = pd.to_datetime(inst_tmp["RecordingStartTime"])

latest = inst_tmp["RecordingStartTime"].dt.year - inst_tmp["Age min"]
earliest = inst_tmp["RecordingStartTime"].dt.year - inst_tmp["Age max"]
mask = inst_tmp["Weathering class"].notna()

if "year_died_latest" not in df_instances.columns:
    df_instances["year_died_latest"] = pd.NA
if "year_died_earliest" not in df_instances.columns:
    df_instances["year_died_earliest"] = pd.NA

df_instances.loc[mask, "year_died_latest"] = np.floor(latest[mask]).astype("Int64")
df_instances.loc[mask, "year_died_earliest"] = np.floor(earliest[mask]).astype("Int64")

df_instances["year_died_latest"] = df_instances["year_died_latest"].astype("Int64")
df_instances["year_died_earliest"] = df_instances["year_died_earliest"].astype("Int64")

df_instances.to_pickle("../data/pkl/df_instances.pkl")

if "year_died_latest" not in df_occurrences.columns or "year_died_earliest" not in df_occurrences.columns:
    occ_years = (
        df_instances.groupby("OccurrenceID")[ ["year_died_latest", "year_died_earliest"] ]
        .min()
    )
    for col in occ_years.columns:
        occ_years[col] = pd.array(occ_years[col], dtype="Int64")
    df_occurrences = df_occurrences.merge(
        occ_years, left_on="ID", right_index=True, how="left",
    )

for col in ["year_died_latest", "year_died_earliest"]:
    if col in df_occurrences.columns:
        df_occurrences[col] = pd.array(
            np.floor(pd.to_numeric(df_occurrences[col], errors="coerce")),
            dtype="Int64",
        )

df_occurrences.to_pickle("../data/pkl/df_occurrences.pkl")

In [ ]:
# Estimate year of death for Briana responses
briana_tmp = df_briana_with_responses.merge(
    df_instances[["UID", "RecordingStartTime"]], on="UID", how="left",
)
briana_tmp = briana_tmp.join(weathering_lookup, on="Weathering class")
briana_tmp["RecordingStartTime"] = pd.to_datetime(briana_tmp["RecordingStartTime"])

latest = briana_tmp["RecordingStartTime"].dt.year - briana_tmp["Age min"]
earliest = briana_tmp["RecordingStartTime"].dt.year - briana_tmp["Age max"]
mask = briana_tmp["Weathering class"].notna()

if "year_died_latest" not in df_briana_with_responses.columns:
    df_briana_with_responses["year_died_latest"] = pd.NA
if "year_died_earliest" not in df_briana_with_responses.columns:
    df_briana_with_responses["year_died_earliest"] = pd.NA

idx = df_briana_with_responses.index[mask]
df_briana_with_responses.loc[idx, "year_died_latest"] = np.floor(latest[mask]).astype("Int64")
df_briana_with_responses.loc[idx, "year_died_earliest"] = np.floor(earliest[mask]).astype("Int64")

df_briana_with_responses["year_died_latest"] = df_briana_with_responses["year_died_latest"].astype("Int64")
df_briana_with_responses["year_died_earliest"] = df_briana_with_responses["year_died_earliest"].astype("Int64")

df_briana_with_responses.to_pickle("../data/pkl/df_briana_with_responses.pkl")

In [17]:
df_fire_with_responses = pd.read_pickle("../data/pkl/df_fire_with_responses.pkl")
df_fire_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,Are there ecomorphable elements?,Articulated?,Bone notes,Buried - Notes,Buried?,...,UPM lo,UPM4 lc,UPM4 lo,UPM4 wc,UPM4 wo,Upper or lower?,Vertebra Portion,Weathering class,What element is this?,upper or lower?
0,A4802CC8-E5E0-439E-B6EC-38F3F46836D0,269,DE54448B-7AAD-4E55-B364-795A6F2888A7,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B1AE1CD6-16E1-4C69-80B4-1DC02EBA1F0D,272,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29428771-CDA7-48BA-87ED-6B52BDE512FB,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36390049-5D37-44EB-AEFE-63651658463E,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,2,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EC8379E0-1868-4CD7-9130-89E546E91755,273,114A785B-804D-4AEB-892B-D6116DF31303,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# NISP (# of bones)
# Merge df_instances with df_occurrences (to get TransectUID)
df_instances_with_occ = df_instances.merge(
    df_occurrences[['ID', 'TransectUID']],
    how='inner',
    left_on='OccurrenceID',
    right_on='ID',
    suffixes=('', '_occ')
)

# Merge with df_transects to get the habitat
df_instances_full = df_instances_with_occ.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='inner',
    left_on='TransectUID',
    right_on='UID',
    suffixes=('', '_transect')
)

In [19]:
df_transect_metadata = df_transects.copy()
df_transect_metadata['area_km2'] = df_transect_metadata['distance_km'] * 0.05
mni_per_transect = df_occurrences['TransectUID'].value_counts()
df_transect_metadata['mni_count'] = df_transect_metadata['UID'].map(mni_per_transect).fillna(0).astype(int)
nisp_per_transect = df_instances_full['TransectUID'].value_counts()
df_transect_metadata['nisp_count'] = df_transect_metadata['UID'].map(nisp_per_transect).fillna(0).astype(int)

In [20]:
# 1. Create a clean Taxon label column
df_occurrences['Taxon Label'] = (
    df_occurrences['Post: Taxon Guess?']
    .fillna(df_occurrences['Pre: Taxon'])
)

df_occurrences['Taxon Label'] = df_occurrences['Taxon Label'].replace({
    '36;37': 'Bovidae (large)'
})
df_occurrences['Taxon Label'] = df_occurrences['Taxon Label'].replace({
    '43;41': 'Bovidae (small)'
})
df_occurrences['Taxon Label'] = df_occurrences['Taxon Label'].replace({
    '42;46': 'Bovidae (small)'
})

# 2. Merge with transect metadata to get habitat

df_occurrences_with_taxon = df_occurrences.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='left',
    left_on='TransectUID',
    right_on='UID'
)
for col in ["year_died_latest", "year_died_earliest"]:
    if col in df_occurrences_with_taxon.columns:
        df_occurrences_with_taxon[col] = pd.array(
            np.floor(pd.to_numeric(df_occurrences_with_taxon[col], errors="coerce")),
            dtype="Int64",
        )

# 3. Create composition matrices
# A. Taxon by Habitat
df_taxon_by_habitat = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='Pre: Transect physical habitat',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# B. Taxon by Transect
df_taxon_by_transect = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='TransectUID',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# 4. Save all to pickle files
import os
os.makedirs("data", exist_ok=True)

df_occurrences_with_taxon.to_pickle("../data/pkl/df_occurrences_with_taxon.pkl")
df_taxon_by_habitat.to_pickle("../data/pkl/df_taxon_by_habitat.pkl")
df_taxon_by_transect.to_pickle("../data/pkl/df_taxon_by_transect.pkl")

In [21]:
# !mkdir -p data
# Save the DataFrame to a pickle file
df_transect_metadata.to_pickle("../data/pkl/df_transect_metadata.pkl")
df_transect_metadata

,UID,Name,start_time,turn_time,end_time,lat_from,long_from,lat_turn,long_turn,lat_to,...,Pre: Notes,Pre: Notes on Transect Start,Pre: OPC Vegetation,Pre: On old reserve?,Pre: Reserve vegetation,Pre: Transect physical habitat,Pre: Transect vegetation,area_km2,mni_count,nisp_count
0,271687,48,2011-07-08 16:09:19,2011-07-08 17:38:38,2011-07-08 17:53:34,0.019397,36.944255,0.019248,36.936132,0.019248,...,start just south of road off grants plains,NaN,NaN,Yes,NaN,grass closed,grass,0.045171,5,54
1,274498,49,2011-07-10 14:59:39,2011-07-10 15:21:22,2011-07-12 12:40:34,0.021680,36.941568,0.021160,36.935927,0.021160,...,NaN,a bit north of road,NaN,Yes,NaN,grass closed,grass,0.031499,4,118
2,277434,50,2011-07-12 15:59:36,2011-07-13 15:05:27,2011-07-13 15:56:27,0.022625,36.930758,0.022605,36.939808,0.022625,...,NaN,heading east,NaN,Yes,NaN,grass closed,grass,0.050026,8,32
3,278888,51,2011-07-13 16:09:31,2011-07-15 12:33:06,2011-07-15 12:47:30,0.023828,36.930668,0.023388,36.938127,0.023388,...,NaN,,NaN,Yes,NaN,grass closed,grass,0.041539,8,181
4,285685,52,2011-07-18 09:28:36,2011-07-18 10:31:19,2011-07-18 11:15:07,0.087638,36.828862,0.087870,36.837802,0.087870,...,NaN,transitional between opn and wooded bushed gra...,NaN,No,NaN,grass closed,grass,0.049721,7,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,7143341,151,2024-08-31 15:43:46,2024-08-31 16:21:51,2024-08-31 17:04:48,0.067312,36.884310,0.067250,36.875153,0.067314,...,NaN,,Acacia drepanolobium,No,Acacia,shrubs open,NaN,0.050002,1,1
145,7144445,152,2024-09-01 10:06:25,2024-09-01 10:44:38,2024-09-01 11:21:38,0.042505,36.859843,0.042510,36.868795,0.042511,...,NaN,,Grassland,No,grass,grass closed,NaN,0.049912,0,0
146,7144723,153,2024-09-01 14:43:29,2024-09-01 15:21:05,2024-09-01 15:48:09,0.035062,36.880343,0.042293,36.880380,0.044200,...,NaN,,Grassland,No,grass,grass closed,NaN,0.050808,1,2
147,7145831,154,2024-09-02 09:13:23,2024-09-02 10:22:04,2024-09-02 11:08:22,0.036177,36.929443,0.036218,36.938410,0.036211,...,NaN,,Acacia drepanolobium,Yes,mixed Acacia dominant,shrubs open,NaN,0.049791,3,14
148,7146177,155,2024-09-02 14:57:49,2024-09-02 15:43:57,2024-09-02 16:36:08,0.065163,36.918823,0.065107,36.927842,0.065112,...,NaN,,Grassland,Yes,grass,grass closed,NaN,0.050166,3,6

In [22]:
output_path = "../data/export/excel/source_data.xlsx"

instances_clean = df_instances.rename(columns=lambda c: c.strip())
occurrences_clean = df_occurrences.rename(columns=lambda c: c.strip())
briana_clean = df_briana_with_responses.rename(columns=lambda c: c.strip())

# normalize instance column names to ensure size-class fields are preserved
inst_col_map = {}
for col in instances_clean.columns:
    key = col.strip().lower()
    if key == "pre: size class":
        inst_col_map[col] = "Pre: Size class"
    elif key == "post: size class":
        inst_col_map[col] = "Post: Size Class"
    elif key == "pre: age":
        inst_col_map[col] = "Pre: Age"
instances_norm = instances_clean.rename(columns=inst_col_map)

inst_cols = ["UID", "Pre: Size class", "Pre: Age", "Post: Size Class"]
instances_subset = instances_norm.reindex(columns=inst_cols)

occ_cols = [
    "ID",
    "TransectUID",
    "Pre: Taxon",
    "Post: Taxon",
    "Taxon Label",
    "Post: Sex",
    "Pre: Sex",
    "Post: Notes on Occurence End",
]
occurrences_subset = occurrences_clean.reindex(columns=occ_cols)

briana_cols = [
    "UID",
    "OccurrenceID",
    "InstanceNumber",
    "Articulated?",
    "Complete?",
    "Innominate Portion",
    "Mandible Portion",
    "Rib Portion",
    "Scapula Portion",
    "Weathering class",
    "What element is this?",
]
briana_subset = briana_clean.reindex(columns=briana_cols)

briana_sheet = (
    briana_subset
    .merge(instances_subset, on="UID", how="left")
    .merge(
        occurrences_subset,
        left_on="OccurrenceID",
        right_on="ID",
        how="left",
    )
    .rename(
        columns={
            "TransectUID": "Transect number",
            "ID": "Occurrence id",
            "InstanceNumber": "Occurrence number",
            "Pre: Age": "Age",
        }
    )
    .reindex(
        columns=[
            "Transect number",
            "Occurrence id",
            "Occurrence number",
            "Pre: Taxon",
            "Post: Taxon",
            "Taxon Label",
            "Post: Sex",
            "Post: Size Class",
            "Age",
            "Pre: Sex",
            "Pre: Size class",
            "Post: Notes on Occurence End",
            "Articulated?",
            "Complete?",
            "Innominate Portion",
            "Mandible Portion",
            "Rib Portion",
            "Scapula Portion",
            "Weathering class",
            "What element is this?",
        ]
    )
)

with pd.ExcelWriter(output_path, engine='xlsxwriter') as writer:
    df_transects.to_excel(writer, sheet_name='Transects', index=False)
    df_occurrences.to_excel(writer, sheet_name='Occurrences', index=False)
    df_instances.to_excel(writer, sheet_name='Instances', index=False)
    df_briana_with_responses.to_excel(writer, sheet_name='Briana', index=False)
    df_fire_with_responses.to_excel(writer, sheet_name='Fire', index=False)
    df_transect_metadata.to_excel(writer, sheet_name='TransectData', index=False)
    briana_sheet.to_excel(writer, sheet_name='OccurrencesBriana', index=False)

print(f"âœ… Excel saved to: {output_path}")

âœ… Excel saved to: ../data/export/excel/source_data.xlsx