In [3]:
import pandas as pd
df_transects = pd.read_pickle("../data/pkl/df_transects.pkl")
df_transects.head()

,UID,Name,start_time,turn_time,end_time,lat_from,long_from,lat_turn,long_turn,lat_to,...,Post: Notes on Transect End,Pre: Ecomorphology habitat,Pre: New Transect?,Pre: Notes,Pre: Notes on Transect Start,Pre: OPC Vegetation,Pre: On old reserve?,Pre: Reserve vegetation,Pre: Transect physical habitat,Pre: Transect vegetation
0,271687,48,2011-07-08 16:09:19,2011-07-08 17:38:38,2011-07-08 17:53:34,0.019397,36.944255,0.019248,36.936132,0.019248,...,"ended at 900m, transect end near bushland",open/tree-less,Yes,start just south of road off grants plains,NaN,NaN,Yes,NaN,grass closed,grass
1,274498,49,2011-07-10 14:59:39,2011-07-10 15:21:22,2011-07-12 12:40:34,0.021680,36.941568,0.021160,36.935927,0.021160,...,NaN,open/tree-less,Yes,NaN,a bit north of road,NaN,Yes,NaN,grass closed,grass
2,277434,50,2011-07-12 15:59:36,2011-07-13 15:05:27,2011-07-13 15:56:27,0.022625,36.930758,0.022605,36.939808,0.022625,...,NaN,open/tree-less,Yes,NaN,heading east,NaN,Yes,NaN,grass closed,grass
3,278888,51,2011-07-13 16:09:31,2011-07-15 12:33:06,2011-07-15 12:47:30,0.023828,36.930668,0.023388,36.938127,0.023388,...,NaN,open/tree-less,Yes,NaN,,NaN,Yes,NaN,grass closed,grass
4,285685,52,2011-07-18 09:28:36,2011-07-18 10:31:19,2011-07-18 11:15:07,0.087638,36.828862,0.087870,36.837802,0.087870,...,3 patches of hyena poop,O;WBG,Yes,NaN,transitional between opn and wooded bushed gra...,NaN,No,NaN,grass closed,grass

In [4]:
df_occurrences = pd.read_pickle("../data/pkl/df_occurrences.pkl")
df_occurrences.head()

,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,Lat,Long,Note,State,Post: Age,...,Post: Taxon guess?,Pre: Age,Pre: Distance spotted,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon
0,1,4354089,1,2003-02-17 09:12:35,2003-02-17 17:14:57,0.042495,36.970267,None,Completed,NaN,...,NaN,adult,0,No,No,"flat, open, short grass",,Unknown,3b-4,Bovidae (large)
1,2,4354089,2,2003-02-17 09:17:26,2003-02-17 17:20:34,0.042522,36.966980,None,Completed,NaN,...,NaN,adult,0,No,No,"very short grass, dirt patch, flat and open \n",,Unknown,4,eland
2,3,4354089,3,2003-02-17 09:55:37,2003-02-17 10:05:08,0.042432,36.966908,None,Completed,NaN,...,NaN,old adult,5,No,No,"flat, short grass",,Unknown,4,zebra
3,4,4354089,4,2003-02-17 10:14:26,2003-02-17 10:15:34,0.042495,36.966773,None,Completed,NaN,...,NaN,adult,0,No,No,"dirt patch, flat",,Unknown,0 - unknown,Mammalia indet
4,5,4354089,5,2003-02-17 10:30:03,2003-02-17 16:08:58,0.042549,36.966055,None,Completed,NaN,...,NaN,adult,16,No,No,"flat, very short grass",,Unknown,3,Bovidae (medium)

In [6]:
df_instances = pd.read_pickle("../data/pkl/df_instances.pkl")
df_instances.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,ID,TransectUID,OccurrenceNumber,RecordingStartTime,RecordingEndTime,...,Pre: Dried skin present?,Pre: Fresh bone(s)?,Pre: Local Context,Pre: Notes - fresh,Pre: Sex,Pre: Size class,Pre: Taxon,Name,DateAdded,AddedBy
0,C3CD24C5-09B7-42DB-A5BE-82C862FCEE6A,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
1,28FC916B-F859-444C-A3B6-24F1040AB291,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,2,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
2,FF2ABC54-0172-4A03-81FE-72BAB7CE4C41,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,3,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
3,43E88323-2CA0-4A29-8552-480BB96E4ACB,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,4,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick
4,24D9C6B4-FADC-4706-B09B-80EAD9F15D57,265,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,5,Briana,265.0,271687.0,1.0,2011-07-08 16:24:01,2011-07-08 16:30:47,...,Yes,Yes,in tall grass patch,dried skin bits,Unknown,3b,zebra,Bone,2019-10-15 00:42:13.370,nick

In [19]:
df_briana_with_responses = pd.read_pickle("../data/pkl/df_briana_with_responses.pkl")
df_briana_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,Are there ecomorphable elements?,Articulated?,Bone notes,Buried - Notes,Buried?,...,UPM lo,UPM4 lc,UPM4 lo,UPM4 wc,UPM4 wo,Upper or lower?,Vertebra Portion,Weathering class,What element is this?,upper or lower?
0,B5E69EAE-E4FF-1B3E-F38B-0EC66DAC8774,1,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,3,calcaneus,NaN
1,789F0CCC-7D1C-816F-F29C-B4E0BB3B82AB,2,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,damage but not sure if caused by carnivore,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,4,hemi-mandible,NaN
2,316C833E-D57B-C57D-6EB9-0F6447D46963,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,1,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN
3,17F84367-F24B-B574-F9CC-0CFF4F414BC0,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,2,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN
4,0FF21BFC-21B9-7915-45B2-5D82706B82B5,3,AED98AE9-DD15-4449-B60D-C9F27A02F2EE,3,Briana,NaN,,,,No,...,NaN,NaN,NaN,NaN,NaN,NaN,,1,hemi-mandible,NaN

In [30]:
df_fire_with_responses = pd.read_pickle("../data/pkl/df_fire_with_responses.pkl")
df_fire_with_responses.head()

,UID,OccurrenceID,TemplateWorkflowID,InstanceNumber,CompletedBy,Are there ecomorphable elements?,Articulated?,Bone notes,Buried - Notes,Buried?,...,UPM lo,UPM4 lc,UPM4 lo,UPM4 wc,UPM4 wo,Upper or lower?,Vertebra Portion,Weathering class,What element is this?,upper or lower?
0,A4802CC8-E5E0-439E-B6EC-38F3F46836D0,269,DE54448B-7AAD-4E55-B364-795A6F2888A7,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B1AE1CD6-16E1-4C69-80B4-1DC02EBA1F0D,272,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29428771-CDA7-48BA-87ED-6B52BDE512FB,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,1,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36390049-5D37-44EB-AEFE-63651658463E,273,651BD177-976C-4D35-8BE9-8DFC3736BA9F,2,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EC8379E0-1868-4CD7-9130-89E546E91755,273,114A785B-804D-4AEB-892B-D6116DF31303,3,Fire,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Filter transects to only those marked as "on old reserve"
df_old_reserve_transects = df_transects[df_transects["Pre: On old reserve?"] == "Yes"].copy()
valid_transect_uids = df_old_reserve_transects['UID']

# Count by 'Pre: Transect physical habitat'
counts = df_old_reserve_transects["Pre: Transect physical habitat"].value_counts()

# Convert to a single-row DataFrame with habitat types as columns
summary_table = pd.DataFrame([counts])
summary_table.index = ['# of transects']

# Step 2: Join df_occurrences to get the habitat info
df_occ_with_habitat = df_occurrences.merge(
    df_old_reserve_transects[['UID', 'Pre: Transect physical habitat']],
    how='inner',
    left_on='TransectUID',
    right_on='UID'
)

# Step 3: Group and count occurrences (MNI)
mni_counts = df_occ_with_habitat['Pre: Transect physical habitat'].value_counts()

# Step 4: Add MNI row to the summary table
summary_table.loc['MNI (n)'] = summary_table.columns.map(mni_counts).fillna(0).astype(int)

# By Taxa
# Filter transects to 'old reserve' only
df_occ_with_habitat['Taxon Label'] = df_occ_with_habitat['Post: Taxon guess?'].fillna(
    df_occ_with_habitat['Pre: Taxon']
)

taxon_summary = df_occ_with_habitat.pivot_table(
    index='Taxon Label',
    columns='Pre: Transect physical habitat',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# Align and append to summary_table
taxon_summary = taxon_summary.reindex(columns=summary_table.columns, fill_value=0)
summary_table = pd.concat([summary_table, taxon_summary])

In [10]:
# km2 covered
# Multiply each transect's distance by 0.05 to estimate area
df_old_reserve_transects['area_km2'] = df_old_reserve_transects['distance_km'] * 0.05

# Sum area per habitat type
area_by_habitat = df_old_reserve_transects.groupby("Pre: Transect physical habitat")["area_km2"].sum()

# Align with column order of summary_table
#area_row = summary_table.columns.map(area_by_habitat).fillna(0).round(2)
area_row = pd.Series(summary_table.columns.map(area_by_habitat)).fillna(0).astype(float).round(2)
# Now assign the row (note: index should match summary_table.columns)
area_row.index = summary_table.columns

# Add to summary_table
summary_table.loc['km2 covered'] = area_row
# summary_table.head()

Pre: Transect physical habitat,grass closed,shrubs open,shrubs closed,trees closed
# of transects,27.0,23.0,18.0,11.0
MNI (n),274.0,229.0,96.0,32.0
,6.0,0.0,0.0,0.0
Aves (medium),1.0,0.0,1.0,0.0
Aves (small),0.0,1.0,1.0,0.0

In [12]:
# Calculate MNI per kmÂ² (avoid division by zero just in case)
mni_row = summary_table.loc['MNI (n)']
area_row = summary_table.loc['km2 covered']

mni_per_km2 = (mni_row / area_row.replace(0, pd.NA)).round().fillna(0)
summary_table.loc['MNI/km2'] = pd.Series(mni_per_km2, index=summary_table.columns)
summary_table.loc['MNI/km2'].apply(type)

Pre: Transect physical habitat
grass closed     <class 'float'>
shrubs open      <class 'float'>
shrubs closed    <class 'float'>
trees closed     <class 'float'>
Name: MNI/km2, dtype: object

In [15]:
# NISP (# of bones)
# Merge df_instances with df_occurrences (to get TransectUID)
df_instances_with_occ = df_instances.merge(
    df_occurrences[['ID', 'TransectUID']],
    how='left',
    left_on='OccurrenceID',
    right_on='ID',
    suffixes=('', '_occ')
)

# Merge with df_transects to get the habitat
df_instances_full = df_instances_with_occ.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='left',
    left_on='TransectUID',
    right_on='UID',
    suffixes=('', '_transect')
)

# Filter to "old reserve" transects (if needed)

df_instances_old_reserve = df_instances_full[df_instances_full["Pre: On old reserve?"] == "Yes"].copy()

# Count instances per habitat (aka NISP)
nisp_counts = df_instances_old_reserve['Pre: Transect physical habitat'].value_counts()
nisp_row = summary_table.columns.map(nisp_counts).fillna(0).astype(int)
summary_table.loc['NISP (# of bones)'] = nisp_row

In [16]:
# NISP/km2
# Get existing rows from the summary table
nisp_row = summary_table.loc['NISP (# of bones)']
area_row = summary_table.loc['km2 covered']

# Calculate NISP per kmÂ², round, and convert to int
nisp_per_km2 = (nisp_row / area_row.replace(0, pd.NA)).round().fillna(0).astype(int)

# Add to the summary table
summary_table.loc['NISP/km2'] = pd.Series(nisp_per_km2, index=summary_table.columns)

In [22]:
# Weathering class percentages
df_briana_with_occ = df_briana_with_responses.merge(
    df_occurrences[['ID', 'TransectUID']],
    how='left',
    left_on='OccurrenceID',
    right_on='ID',
    suffixes=('', '_occ')
)

df_briana_with_occ_transect = df_briana_with_occ.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='left',
    left_on='TransectUID',
    right_on='UID',
    suffixes=('', '_transect')
)

# Only old reserve
df_briana_old_reserve = df_briana_with_occ_transect[
    df_briana_with_occ_transect['Pre: On old reserve?'] == 'Yes'
].copy()

weathering_counts = df_briana_old_reserve.pivot_table(
    index='Weathering class',
    columns='Pre: Transect physical habitat',
    values='UID',
    aggfunc='count',
    fill_value=0
)

weathering_percent = weathering_counts.div(weathering_counts.sum(axis=0), axis=1) * 100
weathering_percent = weathering_percent.round(1)

# Reindex to match summary table column order
weathering_percent = weathering_percent.reindex(columns=summary_table.columns, fill_value=0)

# Add rows to summary table
for label, row in weathering_percent.iterrows():
    summary_table.loc[f'Weathering class {label} (%)'] = row

In [23]:
# Count total instances per habitat (denominator)
nisp_total = df_briana_old_reserve['Pre: Transect physical habitat'].value_counts()

# Count buried instances per habitat (numerator)
buried = df_briana_old_reserve[df_briana_old_reserve['Buried?'] == 'Yes']
buried_counts = buried['Pre: Transect physical habitat'].value_counts()

# Calculate percentage
buried_percent = (buried_counts / nisp_total * 100).round(1)

# Align with summary table columns
buried_row = summary_table.columns.map(buried_percent).fillna(0)

# Add row to summary table
summary_table.loc['% buried bones'] = buried_row

In [24]:
# % bones with any carnivore damage

# Instances with any carnivore damage
# Count where there is *any* non-null damage level
# Count only valid carnivore damage levels (as strings just in case)
valid_damage_levels = {'1', '2', '3', '4'}

has_valid_carn_damage = df_briana_old_reserve[
    df_briana_old_reserve['Carn Damage 1 Level'].astype(str).isin(valid_damage_levels)
]

carn_counts = has_valid_carn_damage['Pre: Transect physical habitat'].value_counts()

# Calculate % per habitat
carn_percent = (carn_counts / nisp_total * 100).round(1)

# Align with summary_table columns
carn_row = summary_table.columns.map(carn_percent).fillna(0)

summary_table.loc['% bones with any carnivore damage'] = carn_row

In [25]:
# View the result
summary_table

Pre: Transect physical habitat,grass closed,shrubs open,shrubs closed,trees closed
# of transects,27.00,23.00,18.00,11.00
MNI (n),274.00,229.00,96.00,32.00
,6.00,0.00,0.00,0.00
Aves (medium),1.00,0.00,1.00,0.00
Aves (small),0.00,1.00,1.00,0.00
Bovidae (large),14.00,18.00,11.00,0.00
Bovidae (medium),16.00,18.00,4.00,2.00
Bovidae (small),16.00,7.00,7.00,2.00
Grant's gazelle,4.00,1.00,0.00,0.00
Mammalia indet,82.00,75.00,39.00,9.00
Rhinocerotidae,0.00,1.00,0.00,0.00
Thompson's gazelle,11.00,4.00,0.00,0.00
buffalo,5.00,12.00,3.00,0.00
cow (domestic),1.00,0.00,0.00,0.00
eland,1.00,1.00,2.00,0.00
elephant,0.00,1.00,0.00,2.00
giraffe,12.00,7.00,6.00,1.00
hare,0.00,0.00,0.00,1.00
hartebeest,2.00,0.00,0.00,0.00
impala,4.00,7.00,1.00,5.00
spotted hyaena,0.00,1.00,0.00,0.00
ungulate,1.00,0.00,2.00,0.00
warthog,18.00,20.00,1.00,1.00
waterbuck,1.00,0.00,4.00,3.00
zebra,79.00,55.00,14.00,6.00
km2 covered,1.34,1.15,0.77,0.59
MNI/km2,204.00,199.00,125.00,54.00
NISP (# of bones),1349.00,1299.00,719.00,147.00
NISP/km2,1007.00,1130.00,934.00,249.00
Weathering class 0 (%),35.70,21.00,17.40,14.20
Weathering class 0-1 (%),6.80,0.00,3.50,0.00
Weathering class 1 (%),20.10,18.30,13.40,23.90
Weathering class 1-2 (%),2.10,0.00,1.90,0.00
Weathering class 2 (%),9.30,11.80,9.00,10.40
Weathering class 2-3 (%),0.90,1.00,1.10,0.00
Weathering class 3 (%),14.10,23.80,12.40,35.80
Weathering class 3-4 (%),0.80,0.50,0.20,7.50
Weathering class 4 (%),6.70,14.00,33.40,6.70
Weathering class 4-5 (%),0.50,0.40,0.30,0.00
Weathering class 5 (%),3.20,9.10,6.90,1.50
Weathering class 6 (%),0.00,0.00,0.30,0.00
% buried bones,4.20,7.30,13.90,6.10
% bones with any carnivore damage,20.90,5.70,5.10,15.60

In [26]:
df_transect_metadata = df_transects.copy()
df_transect_metadata['area_km2'] = df_transect_metadata['distance_km'] * 0.05
mni_per_transect = df_occurrences['TransectUID'].value_counts()
df_transect_metadata['mni_count'] = df_transect_metadata['UID'].map(mni_per_transect).fillna(0).astype(int)
nisp_per_transect = df_instances_full['TransectUID'].value_counts()
df_transect_metadata['nisp_count'] = df_transect_metadata['UID'].map(nisp_per_transect).fillna(0).astype(int)

In [28]:
# DataFrames to Prepare & Save as .pkl
# Name	Description
# df_occurrences_with_taxon	Occurrences + habitat + clean taxon labels
# df_taxon_by_habitat	Taxon abundance matrix by habitat
# df_taxon_by_transect	Taxon abundance matrix by transect
# df_taxon_by_instance (optional)	Taxon occurrence by instance (if needed later)

# 1. Create a clean Taxon label column
df_occurrences['Taxon Label'] = df_occurrences['Post: Taxon guess?'].fillna(
    df_occurrences['Pre: Taxon']
)

# 2. Merge with transect metadata to get habitat

df_occurrences_with_taxon = df_occurrences.merge(
    df_transects[['UID', 'Pre: Transect physical habitat', 'Pre: On old reserve?']],
    how='left',
    left_on='TransectUID',
    right_on='UID'
)

# 3. Create composition matrices
# A. Taxon by Habitat
df_taxon_by_habitat = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='Pre: Transect physical habitat',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# B. Taxon by Transect
df_taxon_by_transect = df_occurrences_with_taxon.pivot_table(
    index='Taxon Label',
    columns='TransectUID',
    values='ID',
    aggfunc='count',
    fill_value=0
)

# 4. Save all to pickle files
import os
os.makedirs("data", exist_ok=True)

df_occurrences_with_taxon.to_pickle("../data/pkl/df_occurrences_with_taxon.pkl")
df_taxon_by_habitat.to_pickle("../data/pkl/df_taxon_by_habitat.pkl")
df_taxon_by_transect.to_pickle("../data/pkl/df_taxon_by_transect.pkl")

In [31]:
output_path = "../data/export/excel/exported_data.xlsx"

with pd.ExcelWriter(output_path, engine='xlsxwriter') as writer:
    df_transects.to_excel(writer, sheet_name='Transects', index=False)
    df_occurrences.to_excel(writer, sheet_name='Occurrences', index=False)
    df_instances.to_excel(writer, sheet_name='Instances', index=False)
    df_briana_with_responses.to_excel(writer, sheet_name='Briana', index=False)
    df_fire_with_responses.to_excel(writer, sheet_name='Fire', index=False)
    summary_table.to_excel(writer, sheet_name='TableData', index=False)
    df_transect_metadata.to_excel(writer, sheet_name='TransectData', index=False)
    
print(f"âœ… Excel saved to: {output_path}")

âœ… Excel saved to: ../data/export/excel/exported_data.xlsx

In [32]:
# !mkdir -p data
# Save the DataFrame to a pickle file
df_transect_metadata.to_pickle("../data/pkl/df_transect_metadata.pkl")